// Code generated by gen-pinyin-parser; DO NOT EDIT.

package pinyin

const (
	start parserState = iota
	stA
	stAI
	stAN
	stANG
	stAO
	stB
	stBA
	stBAI
	stBAN
	stBANG
	stBAO
	stBE
	stBEI
	stBEN
	stBENG
	stBI
	stBIA
	stBIAN
	stBIANG
	stBIAO
	stBIE
	stBIN
	stBING
	stBO
	stBU
	stC
	stCA
	stCAI
	stCAN
	stCANG
	stCAO
	stCE
	stCEI
	stCEN
	stCENG
	stCH
	stCHA
	stCHAI
	stCHAN
	stCHANG
	stCHAO
	stCHE
	stCHEN
	stCHENG
	stCHI
	stCHO
	stCHON
	stCHONG
	stCHOU
	stCHU
	stCHUA
	stCHUAI
	stCHUAN
	stCHUANG
	stCHUI
	stCHUN
	stCHUO
	stCI
	stCO
	stCON
	stCONG
	stCOU
	stCU
	stCUA
	stCUAN
	stCUI
	stCUN
	stCUO
	stD
	stDA
	stDAI
	stDAN
	stDANG
	stDAO
	stDE
	stDEI
	stDEN
	stDENG
	stDI
	stDIA
	stDIAN
	stDIAO
	stDIE
	stDIN
	stDING
	stDIU
	stDO
	stDON
	stDONG
	stDOU
	stDU
	stDUA
	stDUAN
	stDUI
	stDUN
	stDUO
	stE
	stEI
	stEN
	stENG
	stER
	stF
	stFA
	stFAN
	stFANG
	stFE
	stFEI
	stFEN
	stFENG
	stFI
	stFIA
	stFIAO
	stFO
	stFOU
	stFU
	stG
	stGA
	stGAI
	stGAN
	stGANG
	stGAO
	stGE
	stGEI
	stGEN
	stGENG
	stGO
	stGON
	stGONG
	stGOU
	stGU
	stGUA
	stGUAI
	stGUAN
	stGUANG
	stGUI
	stGUN
	stGUO
	stH
	stHA
	stHAI
	stHAN
	stHANG
	stHAO
	stHE
	stHEI
	stHEN
	stHENG
	stHM
	stHO
	stHON
	stHONG
	stHOU
	stHU
	stHUA
	stHUAI
	stHUAN
	stHUANG
	stHUI
	stHUN
	stHUO
	stJ
	stJI
	stJIA
	stJIAN
	stJIANG
	stJIAO
	stJIE
	stJIN
	stJING
	stJIO
	stJION
	stJIONG
	stJIU
	stJU
	stJUA
	stJUAN
	stJUE
	stJUN
	stK
	stKA
	stKAI
	stKAN
	stKANG
	stKAO
	stKE
	stKEI
	stKEN
	stKENG
	stKO
	stKON
	stKONG
	stKOU
	stKU
	stKUA
	stKUAI
	stKUAN
	stKUANG
	stKUI
	stKUN
	stKUO
	stL
	stLA
	stLAI
	stLAN
	stLANG
	stLAO
	stLE
	stLEI
	stLEN
	stLENG
	stLI
	stLIA
	stLIAN
	stLIANG
	stLIAO
	stLIE
	stLIN
	stLING
	stLIU
	stLO
	stLON
	stLONG
	stLOU
	stLU
	stLUA
	stLUAN
	stLUN
	stLUO
	stLÜ
	stLÜE
	stM
	stMA
	stMAI
	stMAN
	stMANG
	stMAO
	stME
	stMEI
	stMEN
	stMENG
	stMI
	stMIA
	stMIAN
	stMIAO
	stMIE
	stMIN
	stMING
	stMIU
	stMO
	stMOU
	stMU
	stN
	stNA
	stNAI
	stNAN
	stNANG
	stNAO
	stNE
	stNEI
	stNEN
	stNENG
	stNG
	stNI
	stNIA
	stNIAN
	stNIANG
	stNIAO
	stNIE
	stNIN
	stNING
	stNIU
	stNO
	stNON
	stNONG
	stNOU
	stNU
	stNUA
	stNUAN
	stNUN
	stNUO
	stNÜ
	stNÜE
	stO
	stOU
	stP
	stPA
	stPAI
	stPAN
	stPANG
	stPAO
	stPE
	stPEI
	stPEN
	stPENG
	stPI
	stPIA
	stPIAN
	stPIAO
	stPIE
	stPIN
	stPING
	stPO
	stPOU
	stPU
	stQ
	stQI
	stQIA
	stQIAN
	stQIANG
	stQIAO
	stQIE
	stQIN
	stQING
	stQIO
	stQION
	stQIONG
	stQIU
	stQU
	stQUA
	stQUAN
	stQUE
	stQUN
	stR
	stRA
	stRAN
	stRANG
	stRAO
	stRE
	stREN
	stRENG
	stRI
	stRO
	stRON
	stRONG
	stROU
	stRU
	stRUA
	stRUAN
	stRUI
	stRUN
	stRUO
	stS
	stSA
	stSAI
	stSAN
	stSANG
	stSAO
	stSE
	stSEN
	stSENG
	stSH
	stSHA
	stSHAI
	stSHAN
	stSHANG
	stSHAO
	stSHE
	stSHEI
	stSHEN
	stSHENG
	stSHI
	stSHO
	stSHOU
	stSHU
	stSHUA
	stSHUAI
	stSHUAN
	stSHUANG
	stSHUI
	stSHUN
	stSHUO
	stSI
	stSO
	stSON
	stSONG
	stSOU
	stSU
	stSUA
	stSUAN
	stSUI
	stSUN
	stSUO
	stT
	stTA
	stTAI
	stTAN
	stTANG
	stTAO
	stTE
	stTEI
	stTEN
	stTENG
	stTI
	stTIA
	stTIAN
	stTIAO
	stTIE
	stTIN
	stTING
	stTO
	stTON
	stTONG
	stTOU
	stTU
	stTUA
	stTUAN
	stTUI
	stTUN
	stTUO
	stW
	stWA
	stWAI
	stWAN
	stWANG
	stWE
	stWEI
	stWEN
	stWENG
	stWO
	stWON
	stWONG
	stWU
	stX
	stXI
	stXIA
	stXIAN
	stXIANG
	stXIAO
	stXIE
	stXIN
	stXING
	stXIO
	stXION
	stXIONG
	stXIU
	stXU
	stXUA
	stXUAN
	stXUE
	stXUN
	stY
	stYA
	stYAN
	stYANG
	stYAO
	stYE
	stYI
	stYIN
	stYING
	stYO
	stYON
	stYONG
	stYOU
	stYU
	stYUA
	stYUAN
	stYUE
	stYUN
	stZ
	stZA
	stZAI
	stZAN
	stZANG
	stZAO
	stZE
	stZEI
	stZEN
	stZENG
	stZH
	stZHA
	stZHAI
	stZHAN
	stZHANG
	stZHAO
	stZHE
	stZHEI
	stZHEN
	stZHENG
	stZHI
	stZHO
	stZHON
	stZHONG
	stZHOU
	stZHU
	stZHUA
	stZHUAI
	stZHUAN
	stZHUANG
	stZHUI
	stZHUN
	stZHUO
	stZI
	stZO
	stZON
	stZONG
	stZOU
	stZU
	stZUA
	stZUAN
	stZUI
	stZUN
	stZUO
)

const (
	A Sound = iota
	O
	E
	ER
	AI
	AO
	OU
	AN
	EN
	ANG
	ENG
	YI
	YA
	YAO
	YE
	YOU
	YAN
	YIN
	YANG
	YING
	YONG
	WU
	WA
	WO
	WAI
	WEI
	WAN
	WEN
	WANG
	WENG
	YU
	YUE
	YUAN
	YUN
	BA
	BO
	BAI
	BEI
	BAO
	BAN
	BEN
	BANG
	BENG
	BI
	BIAO
	BIE
	BIAN
	BIN
	BING
	BU
	PA
	PO
	PAI
	PEI
	PAO
	POU
	PAN
	PEN
	PANG
	PENG
	PI
	PIAO
	PIE
	PIAN
	PIN
	PING
	PU
	MA
	MO
	ME
	MAI
	MEI
	MAO
	MOU
	MAN
	MEN
	MANG
	MENG
	MI
	MIAO
	MIE
	MIU
	MIAN
	MIN
	MING
	MU
	FA
	FO
	FEI
	FOU
	FAN
	FEN
	FANG
	FENG
	FU
	DA
	DE
	DAI
	DEI
	DAO
	DOU
	DAN
	DEN
	DANG
	DENG
	DONG
	DI
	DIAO
	DIE
	DIU
	DIAN
	DING
	DU
	DUO
	DUI
	DUAN
	DUN
	TA
	TE
	TAI
	TEI
	TAO
	TOU
	TAN
	TANG
	TENG
	TONG
	TI
	TIAO
	TIE
	TIAN
	TING
	TU
	TUO
	TUI
	TUAN
	TUN
	NA
	NE
	NAI
	NEI
	NAO
	NOU
	NAN
	NEN
	NANG
	NENG
	NONG
	NI
	NIAO
	NIE
	NIU
	NIAN
	NIN
	NIANG
	NING
	NU
	NUO
	NUAN
	NÜ
	NÜE
	LA
	LE
	LAI
	LEI
	LAO
	LOU
	LAN
	LANG
	LENG
	LONG
	LI
	LIA
	LIAO
	LIE
	LIU
	LIAN
	LIN
	LIANG
	LING
	LU
	LUO
	LUAN
	LUN
	LÜ
	LÜE
	GA
	GE
	GAI
	GEI
	GAO
	GOU
	GAN
	GEN
	GANG
	GENG
	GONG
	GU
	GUA
	GUO
	GUAI
	GUI
	GUAN
	GUN
	GUANG
	KA
	KE
	KAI
	KEI
	KAO
	KOU
	KAN
	KEN
	KANG
	KENG
	KONG
	KU
	KUA
	KUO
	KUAI
	KUI
	KUAN
	KUN
	KUANG
	HA
	HE
	HAI
	HEI
	HAO
	HOU
	HAN
	HEN
	HANG
	HENG
	HONG
	HU
	HUA
	HUO
	HUAI
	HUI
	HUAN
	HUN
	HUANG
	ZA
	ZE
	ZI
	ZAI
	ZEI
	ZAO
	ZOU
	ZAN
	ZEN
	ZANG
	ZENG
	ZONG
	ZU
	ZUO
	ZUI
	ZUAN
	ZUN
	CA
	CE
	CI
	CAI
	CAO
	COU
	CAN
	CEN
	CANG
	CENG
	CONG
	CU
	CUO
	CUI
	CUAN
	CUN
	SA
	SE
	SI
	SAI
	SAO
	SOU
	SAN
	SEN
	SANG
	SENG
	SONG
	SU
	SUO
	SUI
	SUAN
	SUN
	ZHA
	ZHE
	ZHI
	ZHAI
	ZHEI
	ZHAO
	ZHOU
	ZHAN
	ZHEN
	ZHANG
	ZHENG
	ZHONG
	ZHU
	ZHUA
	ZHUO
	ZHUAI
	ZHUI
	ZHUAN
	ZHUN
	ZHUANG
	CHA
	CHE
	CHI
	CHAI
	CHAO
	CHOU
	CHAN
	CHEN
	CHANG
	CHENG
	CHONG
	CHU
	CHUA
	CHUO
	CHUAI
	CHUI
	CHUAN
	CHUN
	CHUANG
	SHA
	SHE
	SHI
	SHAI
	SHEI
	SHAO
	SHOU
	SHAN
	SHEN
	SHANG
	SHENG
	SHU
	SHUA
	SHUO
	SHUAI
	SHUI
	SHUAN
	SHUN
	SHUANG
	RE
	RI
	RAO
	ROU
	RAN
	REN
	RANG
	RENG
	RONG
	RU
	RUA
	RUO
	RUI
	RUAN
	RUN
	JI
	JIA
	JIAO
	JIE
	JIU
	JIAN
	JIN
	JIANG
	JING
	JIONG
	JU
	JUE
	JUAN
	JUN
	QI
	QIA
	QIAO
	QIE
	QIU
	QIAN
	QIN
	QIANG
	QING
	QIONG
	QU
	QUE
	QUAN
	QUN
	XI
	XIA
	XIAO
	XIE
	XIU
	XIAN
	XIN
	XIANG
	XING
	XIONG
	XU
	XUE
	XUAN
	XUN
	FIAO
	N
	NG
	M
	YO
	HM
	LO
	EI
	NUN
	CEI
	WONG
	DIN
	BIANG
	R
)

func (p Sound) String() string {
	switch p {
	case A:
		return "a"
	case O:
		return "o"
	case E:
		return "e"
	case ER:
		return "er"
	case AI:
		return "ai"
	case AO:
		return "ao"
	case OU:
		return "ou"
	case AN:
		return "an"
	case EN:
		return "en"
	case ANG:
		return "ang"
	case ENG:
		return "eng"
	case YI:
		return "yi"
	case YA:
		return "ya"
	case YAO:
		return "yao"
	case YE:
		return "ye"
	case YOU:
		return "you"
	case YAN:
		return "yan"
	case YIN:
		return "yin"
	case YANG:
		return "yang"
	case YING:
		return "ying"
	case YONG:
		return "yong"
	case WU:
		return "wu"
	case WA:
		return "wa"
	case WO:
		return "wo"
	case WAI:
		return "wai"
	case WEI:
		return "wei"
	case WAN:
		return "wan"
	case WEN:
		return "wen"
	case WANG:
		return "wang"
	case WENG:
		return "weng"
	case YU:
		return "yu"
	case YUE:
		return "yue"
	case YUAN:
		return "yuan"
	case YUN:
		return "yun"
	case BA:
		return "ba"
	case BO:
		return "bo"
	case BAI:
		return "bai"
	case BEI:
		return "bei"
	case BAO:
		return "bao"
	case BAN:
		return "ban"
	case BEN:
		return "ben"
	case BANG:
		return "bang"
	case BENG:
		return "beng"
	case BI:
		return "bi"
	case BIAO:
		return "biao"
	case BIE:
		return "bie"
	case BIAN:
		return "bian"
	case BIN:
		return "bin"
	case BING:
		return "bing"
	case BU:
		return "bu"
	case PA:
		return "pa"
	case PO:
		return "po"
	case PAI:
		return "pai"
	case PEI:
		return "pei"
	case PAO:
		return "pao"
	case POU:
		return "pou"
	case PAN:
		return "pan"
	case PEN:
		return "pen"
	case PANG:
		return "pang"
	case PENG:
		return "peng"
	case PI:
		return "pi"
	case PIAO:
		return "piao"
	case PIE:
		return "pie"
	case PIAN:
		return "pian"
	case PIN:
		return "pin"
	case PING:
		return "ping"
	case PU:
		return "pu"
	case MA:
		return "ma"
	case MO:
		return "mo"
	case ME:
		return "me"
	case MAI:
		return "mai"
	case MEI:
		return "mei"
	case MAO:
		return "mao"
	case MOU:
		return "mou"
	case MAN:
		return "man"
	case MEN:
		return "men"
	case MANG:
		return "mang"
	case MENG:
		return "meng"
	case MI:
		return "mi"
	case MIAO:
		return "miao"
	case MIE:
		return "mie"
	case MIU:
		return "miu"
	case MIAN:
		return "mian"
	case MIN:
		return "min"
	case MING:
		return "ming"
	case MU:
		return "mu"
	case FA:
		return "fa"
	case FO:
		return "fo"
	case FEI:
		return "fei"
	case FOU:
		return "fou"
	case FAN:
		return "fan"
	case FEN:
		return "fen"
	case FANG:
		return "fang"
	case FENG:
		return "feng"
	case FU:
		return "fu"
	case DA:
		return "da"
	case DE:
		return "de"
	case DAI:
		return "dai"
	case DEI:
		return "dei"
	case DAO:
		return "dao"
	case DOU:
		return "dou"
	case DAN:
		return "dan"
	case DEN:
		return "den"
	case DANG:
		return "dang"
	case DENG:
		return "deng"
	case DONG:
		return "dong"
	case DI:
		return "di"
	case DIAO:
		return "diao"
	case DIE:
		return "die"
	case DIU:
		return "diu"
	case DIAN:
		return "dian"
	case DING:
		return "ding"
	case DU:
		return "du"
	case DUO:
		return "duo"
	case DUI:
		return "dui"
	case DUAN:
		return "duan"
	case DUN:
		return "dun"
	case TA:
		return "ta"
	case TE:
		return "te"
	case TAI:
		return "tai"
	case TEI:
		return "tei"
	case TAO:
		return "tao"
	case TOU:
		return "tou"
	case TAN:
		return "tan"
	case TANG:
		return "tang"
	case TENG:
		return "teng"
	case TONG:
		return "tong"
	case TI:
		return "ti"
	case TIAO:
		return "tiao"
	case TIE:
		return "tie"
	case TIAN:
		return "tian"
	case TING:
		return "ting"
	case TU:
		return "tu"
	case TUO:
		return "tuo"
	case TUI:
		return "tui"
	case TUAN:
		return "tuan"
	case TUN:
		return "tun"
	case NA:
		return "na"
	case NE:
		return "ne"
	case NAI:
		return "nai"
	case NEI:
		return "nei"
	case NAO:
		return "nao"
	case NOU:
		return "nou"
	case NAN:
		return "nan"
	case NEN:
		return "nen"
	case NANG:
		return "nang"
	case NENG:
		return "neng"
	case NONG:
		return "nong"
	case NI:
		return "ni"
	case NIAO:
		return "niao"
	case NIE:
		return "nie"
	case NIU:
		return "niu"
	case NIAN:
		return "nian"
	case NIN:
		return "nin"
	case NIANG:
		return "niang"
	case NING:
		return "ning"
	case NU:
		return "nu"
	case NUO:
		return "nuo"
	case NUAN:
		return "nuan"
	case NÜ:
		return "nü"
	case NÜE:
		return "nüe"
	case LA:
		return "la"
	case LE:
		return "le"
	case LAI:
		return "lai"
	case LEI:
		return "lei"
	case LAO:
		return "lao"
	case LOU:
		return "lou"
	case LAN:
		return "lan"
	case LANG:
		return "lang"
	case LENG:
		return "leng"
	case LONG:
		return "long"
	case LI:
		return "li"
	case LIA:
		return "lia"
	case LIAO:
		return "liao"
	case LIE:
		return "lie"
	case LIU:
		return "liu"
	case LIAN:
		return "lian"
	case LIN:
		return "lin"
	case LIANG:
		return "liang"
	case LING:
		return "ling"
	case LU:
		return "lu"
	case LUO:
		return "luo"
	case LUAN:
		return "luan"
	case LUN:
		return "lun"
	case LÜ:
		return "lü"
	case LÜE:
		return "lüe"
	case GA:
		return "ga"
	case GE:
		return "ge"
	case GAI:
		return "gai"
	case GEI:
		return "gei"
	case GAO:
		return "gao"
	case GOU:
		return "gou"
	case GAN:
		return "gan"
	case GEN:
		return "gen"
	case GANG:
		return "gang"
	case GENG:
		return "geng"
	case GONG:
		return "gong"
	case GU:
		return "gu"
	case GUA:
		return "gua"
	case GUO:
		return "guo"
	case GUAI:
		return "guai"
	case GUI:
		return "gui"
	case GUAN:
		return "guan"
	case GUN:
		return "gun"
	case GUANG:
		return "guang"
	case KA:
		return "ka"
	case KE:
		return "ke"
	case KAI:
		return "kai"
	case KEI:
		return "kei"
	case KAO:
		return "kao"
	case KOU:
		return "kou"
	case KAN:
		return "kan"
	case KEN:
		return "ken"
	case KANG:
		return "kang"
	case KENG:
		return "keng"
	case KONG:
		return "kong"
	case KU:
		return "ku"
	case KUA:
		return "kua"
	case KUO:
		return "kuo"
	case KUAI:
		return "kuai"
	case KUI:
		return "kui"
	case KUAN:
		return "kuan"
	case KUN:
		return "kun"
	case KUANG:
		return "kuang"
	case HA:
		return "ha"
	case HE:
		return "he"
	case HAI:
		return "hai"
	case HEI:
		return "hei"
	case HAO:
		return "hao"
	case HOU:
		return "hou"
	case HAN:
		return "han"
	case HEN:
		return "hen"
	case HANG:
		return "hang"
	case HENG:
		return "heng"
	case HONG:
		return "hong"
	case HU:
		return "hu"
	case HUA:
		return "hua"
	case HUO:
		return "huo"
	case HUAI:
		return "huai"
	case HUI:
		return "hui"
	case HUAN:
		return "huan"
	case HUN:
		return "hun"
	case HUANG:
		return "huang"
	case ZA:
		return "za"
	case ZE:
		return "ze"
	case ZI:
		return "zi"
	case ZAI:
		return "zai"
	case ZEI:
		return "zei"
	case ZAO:
		return "zao"
	case ZOU:
		return "zou"
	case ZAN:
		return "zan"
	case ZEN:
		return "zen"
	case ZANG:
		return "zang"
	case ZENG:
		return "zeng"
	case ZONG:
		return "zong"
	case ZU:
		return "zu"
	case ZUO:
		return "zuo"
	case ZUI:
		return "zui"
	case ZUAN:
		return "zuan"
	case ZUN:
		return "zun"
	case CA:
		return "ca"
	case CE:
		return "ce"
	case CI:
		return "ci"
	case CAI:
		return "cai"
	case CAO:
		return "cao"
	case COU:
		return "cou"
	case CAN:
		return "can"
	case CEN:
		return "cen"
	case CANG:
		return "cang"
	case CENG:
		return "ceng"
	case CONG:
		return "cong"
	case CU:
		return "cu"
	case CUO:
		return "cuo"
	case CUI:
		return "cui"
	case CUAN:
		return "cuan"
	case CUN:
		return "cun"
	case SA:
		return "sa"
	case SE:
		return "se"
	case SI:
		return "si"
	case SAI:
		return "sai"
	case SAO:
		return "sao"
	case SOU:
		return "sou"
	case SAN:
		return "san"
	case SEN:
		return "sen"
	case SANG:
		return "sang"
	case SENG:
		return "seng"
	case SONG:
		return "song"
	case SU:
		return "su"
	case SUO:
		return "suo"
	case SUI:
		return "sui"
	case SUAN:
		return "suan"
	case SUN:
		return "sun"
	case ZHA:
		return "zha"
	case ZHE:
		return "zhe"
	case ZHI:
		return "zhi"
	case ZHAI:
		return "zhai"
	case ZHEI:
		return "zhei"
	case ZHAO:
		return "zhao"
	case ZHOU:
		return "zhou"
	case ZHAN:
		return "zhan"
	case ZHEN:
		return "zhen"
	case ZHANG:
		return "zhang"
	case ZHENG:
		return "zheng"
	case ZHONG:
		return "zhong"
	case ZHU:
		return "zhu"
	case ZHUA:
		return "zhua"
	case ZHUO:
		return "zhuo"
	case ZHUAI:
		return "zhuai"
	case ZHUI:
		return "zhui"
	case ZHUAN:
		return "zhuan"
	case ZHUN:
		return "zhun"
	case ZHUANG:
		return "zhuang"
	case CHA:
		return "cha"
	case CHE:
		return "che"
	case CHI:
		return "chi"
	case CHAI:
		return "chai"
	case CHAO:
		return "chao"
	case CHOU:
		return "chou"
	case CHAN:
		return "chan"
	case CHEN:
		return "chen"
	case CHANG:
		return "chang"
	case CHENG:
		return "cheng"
	case CHONG:
		return "chong"
	case CHU:
		return "chu"
	case CHUA:
		return "chua"
	case CHUO:
		return "chuo"
	case CHUAI:
		return "chuai"
	case CHUI:
		return "chui"
	case CHUAN:
		return "chuan"
	case CHUN:
		return "chun"
	case CHUANG:
		return "chuang"
	case SHA:
		return "sha"
	case SHE:
		return "she"
	case SHI:
		return "shi"
	case SHAI:
		return "shai"
	case SHEI:
		return "shei"
	case SHAO:
		return "shao"
	case SHOU:
		return "shou"
	case SHAN:
		return "shan"
	case SHEN:
		return "shen"
	case SHANG:
		return "shang"
	case SHENG:
		return "sheng"
	case SHU:
		return "shu"
	case SHUA:
		return "shua"
	case SHUO:
		return "shuo"
	case SHUAI:
		return "shuai"
	case SHUI:
		return "shui"
	case SHUAN:
		return "shuan"
	case SHUN:
		return "shun"
	case SHUANG:
		return "shuang"
	case RE:
		return "re"
	case RI:
		return "ri"
	case RAO:
		return "rao"
	case ROU:
		return "rou"
	case RAN:
		return "ran"
	case REN:
		return "ren"
	case RANG:
		return "rang"
	case RENG:
		return "reng"
	case RONG:
		return "rong"
	case RU:
		return "ru"
	case RUA:
		return "rua"
	case RUO:
		return "ruo"
	case RUI:
		return "rui"
	case RUAN:
		return "ruan"
	case RUN:
		return "run"
	case JI:
		return "ji"
	case JIA:
		return "jia"
	case JIAO:
		return "jiao"
	case JIE:
		return "jie"
	case JIU:
		return "jiu"
	case JIAN:
		return "jian"
	case JIN:
		return "jin"
	case JIANG:
		return "jiang"
	case JING:
		return "jing"
	case JIONG:
		return "jiong"
	case JU:
		return "ju"
	case JUE:
		return "jue"
	case JUAN:
		return "juan"
	case JUN:
		return "jun"
	case QI:
		return "qi"
	case QIA:
		return "qia"
	case QIAO:
		return "qiao"
	case QIE:
		return "qie"
	case QIU:
		return "qiu"
	case QIAN:
		return "qian"
	case QIN:
		return "qin"
	case QIANG:
		return "qiang"
	case QING:
		return "qing"
	case QIONG:
		return "qiong"
	case QU:
		return "qu"
	case QUE:
		return "que"
	case QUAN:
		return "quan"
	case QUN:
		return "qun"
	case XI:
		return "xi"
	case XIA:
		return "xia"
	case XIAO:
		return "xiao"
	case XIE:
		return "xie"
	case XIU:
		return "xiu"
	case XIAN:
		return "xian"
	case XIN:
		return "xin"
	case XIANG:
		return "xiang"
	case XING:
		return "xing"
	case XIONG:
		return "xiong"
	case XU:
		return "xu"
	case XUE:
		return "xue"
	case XUAN:
		return "xuan"
	case XUN:
		return "xun"
	case FIAO:
		return "fiao"
	case N:
		return "n"
	case NG:
		return "ng"
	case M:
		return "m"
	case YO:
		return "yo"
	case HM:
		return "hm"
	case LO:
		return "lo"
	case EI:
		return "ei"
	case NUN:
		return "nun"
	case CEI:
		return "cei"
	case WONG:
		return "wong"
	case DIN:
		return "din"
	case BIANG:
		return "biang"
	case R:
		return "r"
	default:
		return "?"
	}
}

func (p parserState) Sound() (bool, Sound) {
	switch p {
	case stA:
		return true, A
	case stO:
		return true, O
	case stE:
		return true, E
	case stER:
		return true, ER
	case stAI:
		return true, AI
	case stAO:
		return true, AO
	case stOU:
		return true, OU
	case stAN:
		return true, AN
	case stEN:
		return true, EN
	case stANG:
		return true, ANG
	case stENG:
		return true, ENG
	case stYI:
		return true, YI
	case stYA:
		return true, YA
	case stYAO:
		return true, YAO
	case stYE:
		return true, YE
	case stYOU:
		return true, YOU
	case stYAN:
		return true, YAN
	case stYIN:
		return true, YIN
	case stYANG:
		return true, YANG
	case stYING:
		return true, YING
	case stYONG:
		return true, YONG
	case stWU:
		return true, WU
	case stWA:
		return true, WA
	case stWO:
		return true, WO
	case stWAI:
		return true, WAI
	case stWEI:
		return true, WEI
	case stWAN:
		return true, WAN
	case stWEN:
		return true, WEN
	case stWANG:
		return true, WANG
	case stWENG:
		return true, WENG
	case stYU:
		return true, YU
	case stYUE:
		return true, YUE
	case stYUAN:
		return true, YUAN
	case stYUN:
		return true, YUN
	case stBA:
		return true, BA
	case stBO:
		return true, BO
	case stBAI:
		return true, BAI
	case stBEI:
		return true, BEI
	case stBAO:
		return true, BAO
	case stBAN:
		return true, BAN
	case stBEN:
		return true, BEN
	case stBANG:
		return true, BANG
	case stBENG:
		return true, BENG
	case stBI:
		return true, BI
	case stBIAO:
		return true, BIAO
	case stBIE:
		return true, BIE
	case stBIAN:
		return true, BIAN
	case stBIN:
		return true, BIN
	case stBING:
		return true, BING
	case stBU:
		return true, BU
	case stPA:
		return true, PA
	case stPO:
		return true, PO
	case stPAI:
		return true, PAI
	case stPEI:
		return true, PEI
	case stPAO:
		return true, PAO
	case stPOU:
		return true, POU
	case stPAN:
		return true, PAN
	case stPEN:
		return true, PEN
	case stPANG:
		return true, PANG
	case stPENG:
		return true, PENG
	case stPI:
		return true, PI
	case stPIAO:
		return true, PIAO
	case stPIE:
		return true, PIE
	case stPIAN:
		return true, PIAN
	case stPIN:
		return true, PIN
	case stPING:
		return true, PING
	case stPU:
		return true, PU
	case stMA:
		return true, MA
	case stMO:
		return true, MO
	case stME:
		return true, ME
	case stMAI:
		return true, MAI
	case stMEI:
		return true, MEI
	case stMAO:
		return true, MAO
	case stMOU:
		return true, MOU
	case stMAN:
		return true, MAN
	case stMEN:
		return true, MEN
	case stMANG:
		return true, MANG
	case stMENG:
		return true, MENG
	case stMI:
		return true, MI
	case stMIAO:
		return true, MIAO
	case stMIE:
		return true, MIE
	case stMIU:
		return true, MIU
	case stMIAN:
		return true, MIAN
	case stMIN:
		return true, MIN
	case stMING:
		return true, MING
	case stMU:
		return true, MU
	case stFA:
		return true, FA
	case stFO:
		return true, FO
	case stFEI:
		return true, FEI
	case stFOU:
		return true, FOU
	case stFAN:
		return true, FAN
	case stFEN:
		return true, FEN
	case stFANG:
		return true, FANG
	case stFENG:
		return true, FENG
	case stFU:
		return true, FU
	case stDA:
		return true, DA
	case stDE:
		return true, DE
	case stDAI:
		return true, DAI
	case stDEI:
		return true, DEI
	case stDAO:
		return true, DAO
	case stDOU:
		return true, DOU
	case stDAN:
		return true, DAN
	case stDEN:
		return true, DEN
	case stDANG:
		return true, DANG
	case stDENG:
		return true, DENG
	case stDONG:
		return true, DONG
	case stDI:
		return true, DI
	case stDIAO:
		return true, DIAO
	case stDIE:
		return true, DIE
	case stDIU:
		return true, DIU
	case stDIAN:
		return true, DIAN
	case stDING:
		return true, DING
	case stDU:
		return true, DU
	case stDUO:
		return true, DUO
	case stDUI:
		return true, DUI
	case stDUAN:
		return true, DUAN
	case stDUN:
		return true, DUN
	case stTA:
		return true, TA
	case stTE:
		return true, TE
	case stTAI:
		return true, TAI
	case stTEI:
		return true, TEI
	case stTAO:
		return true, TAO
	case stTOU:
		return true, TOU
	case stTAN:
		return true, TAN
	case stTANG:
		return true, TANG
	case stTENG:
		return true, TENG
	case stTONG:
		return true, TONG
	case stTI:
		return true, TI
	case stTIAO:
		return true, TIAO
	case stTIE:
		return true, TIE
	case stTIAN:
		return true, TIAN
	case stTING:
		return true, TING
	case stTU:
		return true, TU
	case stTUO:
		return true, TUO
	case stTUI:
		return true, TUI
	case stTUAN:
		return true, TUAN
	case stTUN:
		return true, TUN
	case stNA:
		return true, NA
	case stNE:
		return true, NE
	case stNAI:
		return true, NAI
	case stNEI:
		return true, NEI
	case stNAO:
		return true, NAO
	case stNOU:
		return true, NOU
	case stNAN:
		return true, NAN
	case stNEN:
		return true, NEN
	case stNANG:
		return true, NANG
	case stNENG:
		return true, NENG
	case stNONG:
		return true, NONG
	case stNI:
		return true, NI
	case stNIAO:
		return true, NIAO
	case stNIE:
		return true, NIE
	case stNIU:
		return true, NIU
	case stNIAN:
		return true, NIAN
	case stNIN:
		return true, NIN
	case stNIANG:
		return true, NIANG
	case stNING:
		return true, NING
	case stNU:
		return true, NU
	case stNUO:
		return true, NUO
	case stNUAN:
		return true, NUAN
	case stNÜ:
		return true, NÜ
	case stNÜE:
		return true, NÜE
	case stLA:
		return true, LA
	case stLE:
		return true, LE
	case stLAI:
		return true, LAI
	case stLEI:
		return true, LEI
	case stLAO:
		return true, LAO
	case stLOU:
		return true, LOU
	case stLAN:
		return true, LAN
	case stLANG:
		return true, LANG
	case stLENG:
		return true, LENG
	case stLONG:
		return true, LONG
	case stLI:
		return true, LI
	case stLIA:
		return true, LIA
	case stLIAO:
		return true, LIAO
	case stLIE:
		return true, LIE
	case stLIU:
		return true, LIU
	case stLIAN:
		return true, LIAN
	case stLIN:
		return true, LIN
	case stLIANG:
		return true, LIANG
	case stLING:
		return true, LING
	case stLU:
		return true, LU
	case stLUO:
		return true, LUO
	case stLUAN:
		return true, LUAN
	case stLUN:
		return true, LUN
	case stLÜ:
		return true, LÜ
	case stLÜE:
		return true, LÜE
	case stGA:
		return true, GA
	case stGE:
		return true, GE
	case stGAI:
		return true, GAI
	case stGEI:
		return true, GEI
	case stGAO:
		return true, GAO
	case stGOU:
		return true, GOU
	case stGAN:
		return true, GAN
	case stGEN:
		return true, GEN
	case stGANG:
		return true, GANG
	case stGENG:
		return true, GENG
	case stGONG:
		return true, GONG
	case stGU:
		return true, GU
	case stGUA:
		return true, GUA
	case stGUO:
		return true, GUO
	case stGUAI:
		return true, GUAI
	case stGUI:
		return true, GUI
	case stGUAN:
		return true, GUAN
	case stGUN:
		return true, GUN
	case stGUANG:
		return true, GUANG
	case stKA:
		return true, KA
	case stKE:
		return true, KE
	case stKAI:
		return true, KAI
	case stKEI:
		return true, KEI
	case stKAO:
		return true, KAO
	case stKOU:
		return true, KOU
	case stKAN:
		return true, KAN
	case stKEN:
		return true, KEN
	case stKANG:
		return true, KANG
	case stKENG:
		return true, KENG
	case stKONG:
		return true, KONG
	case stKU:
		return true, KU
	case stKUA:
		return true, KUA
	case stKUO:
		return true, KUO
	case stKUAI:
		return true, KUAI
	case stKUI:
		return true, KUI
	case stKUAN:
		return true, KUAN
	case stKUN:
		return true, KUN
	case stKUANG:
		return true, KUANG
	case stHA:
		return true, HA
	case stHE:
		return true, HE
	case stHAI:
		return true, HAI
	case stHEI:
		return true, HEI
	case stHAO:
		return true, HAO
	case stHOU:
		return true, HOU
	case stHAN:
		return true, HAN
	case stHEN:
		return true, HEN
	case stHANG:
		return true, HANG
	case stHENG:
		return true, HENG
	case stHONG:
		return true, HONG
	case stHU:
		return true, HU
	case stHUA:
		return true, HUA
	case stHUO:
		return true, HUO
	case stHUAI:
		return true, HUAI
	case stHUI:
		return true, HUI
	case stHUAN:
		return true, HUAN
	case stHUN:
		return true, HUN
	case stHUANG:
		return true, HUANG
	case stZA:
		return true, ZA
	case stZE:
		return true, ZE
	case stZI:
		return true, ZI
	case stZAI:
		return true, ZAI
	case stZEI:
		return true, ZEI
	case stZAO:
		return true, ZAO
	case stZOU:
		return true, ZOU
	case stZAN:
		return true, ZAN
	case stZEN:
		return true, ZEN
	case stZANG:
		return true, ZANG
	case stZENG:
		return true, ZENG
	case stZONG:
		return true, ZONG
	case stZU:
		return true, ZU
	case stZUO:
		return true, ZUO
	case stZUI:
		return true, ZUI
	case stZUAN:
		return true, ZUAN
	case stZUN:
		return true, ZUN
	case stCA:
		return true, CA
	case stCE:
		return true, CE
	case stCI:
		return true, CI
	case stCAI:
		return true, CAI
	case stCAO:
		return true, CAO
	case stCOU:
		return true, COU
	case stCAN:
		return true, CAN
	case stCEN:
		return true, CEN
	case stCANG:
		return true, CANG
	case stCENG:
		return true, CENG
	case stCONG:
		return true, CONG
	case stCU:
		return true, CU
	case stCUO:
		return true, CUO
	case stCUI:
		return true, CUI
	case stCUAN:
		return true, CUAN
	case stCUN:
		return true, CUN
	case stSA:
		return true, SA
	case stSE:
		return true, SE
	case stSI:
		return true, SI
	case stSAI:
		return true, SAI
	case stSAO:
		return true, SAO
	case stSOU:
		return true, SOU
	case stSAN:
		return true, SAN
	case stSEN:
		return true, SEN
	case stSANG:
		return true, SANG
	case stSENG:
		return true, SENG
	case stSONG:
		return true, SONG
	case stSU:
		return true, SU
	case stSUO:
		return true, SUO
	case stSUI:
		return true, SUI
	case stSUAN:
		return true, SUAN
	case stSUN:
		return true, SUN
	case stZHA:
		return true, ZHA
	case stZHE:
		return true, ZHE
	case stZHI:
		return true, ZHI
	case stZHAI:
		return true, ZHAI
	case stZHEI:
		return true, ZHEI
	case stZHAO:
		return true, ZHAO
	case stZHOU:
		return true, ZHOU
	case stZHAN:
		return true, ZHAN
	case stZHEN:
		return true, ZHEN
	case stZHANG:
		return true, ZHANG
	case stZHENG:
		return true, ZHENG
	case stZHONG:
		return true, ZHONG
	case stZHU:
		return true, ZHU
	case stZHUA:
		return true, ZHUA
	case stZHUO:
		return true, ZHUO
	case stZHUAI:
		return true, ZHUAI
	case stZHUI:
		return true, ZHUI
	case stZHUAN:
		return true, ZHUAN
	case stZHUN:
		return true, ZHUN
	case stZHUANG:
		return true, ZHUANG
	case stCHA:
		return true, CHA
	case stCHE:
		return true, CHE
	case stCHI:
		return true, CHI
	case stCHAI:
		return true, CHAI
	case stCHAO:
		return true, CHAO
	case stCHOU:
		return true, CHOU
	case stCHAN:
		return true, CHAN
	case stCHEN:
		return true, CHEN
	case stCHANG:
		return true, CHANG
	case stCHENG:
		return true, CHENG
	case stCHONG:
		return true, CHONG
	case stCHU:
		return true, CHU
	case stCHUA:
		return true, CHUA
	case stCHUO:
		return true, CHUO
	case stCHUAI:
		return true, CHUAI
	case stCHUI:
		return true, CHUI
	case stCHUAN:
		return true, CHUAN
	case stCHUN:
		return true, CHUN
	case stCHUANG:
		return true, CHUANG
	case stSHA:
		return true, SHA
	case stSHE:
		return true, SHE
	case stSHI:
		return true, SHI
	case stSHAI:
		return true, SHAI
	case stSHEI:
		return true, SHEI
	case stSHAO:
		return true, SHAO
	case stSHOU:
		return true, SHOU
	case stSHAN:
		return true, SHAN
	case stSHEN:
		return true, SHEN
	case stSHANG:
		return true, SHANG
	case stSHENG:
		return true, SHENG
	case stSHU:
		return true, SHU
	case stSHUA:
		return true, SHUA
	case stSHUO:
		return true, SHUO
	case stSHUAI:
		return true, SHUAI
	case stSHUI:
		return true, SHUI
	case stSHUAN:
		return true, SHUAN
	case stSHUN:
		return true, SHUN
	case stSHUANG:
		return true, SHUANG
	case stRE:
		return true, RE
	case stRI:
		return true, RI
	case stRAO:
		return true, RAO
	case stROU:
		return true, ROU
	case stRAN:
		return true, RAN
	case stREN:
		return true, REN
	case stRANG:
		return true, RANG
	case stRENG:
		return true, RENG
	case stRONG:
		return true, RONG
	case stRU:
		return true, RU
	case stRUA:
		return true, RUA
	case stRUO:
		return true, RUO
	case stRUI:
		return true, RUI
	case stRUAN:
		return true, RUAN
	case stRUN:
		return true, RUN
	case stJI:
		return true, JI
	case stJIA:
		return true, JIA
	case stJIAO:
		return true, JIAO
	case stJIE:
		return true, JIE
	case stJIU:
		return true, JIU
	case stJIAN:
		return true, JIAN
	case stJIN:
		return true, JIN
	case stJIANG:
		return true, JIANG
	case stJING:
		return true, JING
	case stJIONG:
		return true, JIONG
	case stJU:
		return true, JU
	case stJUE:
		return true, JUE
	case stJUAN:
		return true, JUAN
	case stJUN:
		return true, JUN
	case stQI:
		return true, QI
	case stQIA:
		return true, QIA
	case stQIAO:
		return true, QIAO
	case stQIE:
		return true, QIE
	case stQIU:
		return true, QIU
	case stQIAN:
		return true, QIAN
	case stQIN:
		return true, QIN
	case stQIANG:
		return true, QIANG
	case stQING:
		return true, QING
	case stQIONG:
		return true, QIONG
	case stQU:
		return true, QU
	case stQUE:
		return true, QUE
	case stQUAN:
		return true, QUAN
	case stQUN:
		return true, QUN
	case stXI:
		return true, XI
	case stXIA:
		return true, XIA
	case stXIAO:
		return true, XIAO
	case stXIE:
		return true, XIE
	case stXIU:
		return true, XIU
	case stXIAN:
		return true, XIAN
	case stXIN:
		return true, XIN
	case stXIANG:
		return true, XIANG
	case stXING:
		return true, XING
	case stXIONG:
		return true, XIONG
	case stXU:
		return true, XU
	case stXUE:
		return true, XUE
	case stXUAN:
		return true, XUAN
	case stXUN:
		return true, XUN
	case stFIAO:
		return true, FIAO
	case stN:
		return true, N
	case stNG:
		return true, NG
	case stM:
		return true, M
	case stYO:
		return true, YO
	case stHM:
		return true, HM
	case stLO:
		return true, LO
	case stEI:
		return true, EI
	case stNUN:
		return true, NUN
	case stCEI:
		return true, CEI
	case stWONG:
		return true, WONG
	case stDIN:
		return true, DIN
	case stBIANG:
		return true, BIANG
	case stR:
		return true, R
	default:
		return false, 0
	}
}

func (p parserState) next(r rune) (bool, parserState) {
	switch p {
	case start:
		switch r {
		case ' ':
			return true, start
		case 'a':
			return true, stA
		case 'b':
			return true, stB
		case 'c':
			return true, stC
		case 'd':
			return true, stD
		case 'e':
			return true, stE
		case 'f':
			return true, stF
		case 'g':
			return true, stG
		case 'h':
			return true, stH
		case 'j':
			return true, stJ
		case 'k':
			return true, stK
		case 'l':
			return true, stL
		case 'm':
			return true, stM
		case 'n':
			return true, stN
		case 'o':
			return true, stO
		case 'p':
			return true, stP
		case 'q':
			return true, stQ
		case 'r':
			return true, stR
		case 's':
			return true, stS
		case 't':
			return true, stT
		case 'w':
			return true, stW
		case 'x':
			return true, stX
		case 'y':
			return true, stY
		case 'z':
			return true, stZ
		}
	case stA:
		switch r {
		case 'i':
			return true, stAI
		case 'n':
			return true, stAN
		case 'o':
			return true, stAO
		}
	case stAN:
		switch r {
		case 'g':
			return true, stANG
		}
	case stB:
		switch r {
		case 'a':
			return true, stBA
		case 'e':
			return true, stBE
		case 'i':
			return true, stBI
		case 'o':
			return true, stBO
		case 'u':
			return true, stBU
		}
	case stBA:
		switch r {
		case 'i':
			return true, stBAI
		case 'n':
			return true, stBAN
		case 'o':
			return true, stBAO
		}
	case stBAN:
		switch r {
		case 'g':
			return true, stBANG
		}
	case stBE:
		switch r {
		case 'i':
			return true, stBEI
		case 'n':
			return true, stBEN
		}
	case stBEN:
		switch r {
		case 'g':
			return true, stBENG
		}
	case stBI:
		switch r {
		case 'a':
			return true, stBIA
		case 'e':
			return true, stBIE
		case 'n':
			return true, stBIN
		}
	case stBIA:
		switch r {
		case 'n':
			return true, stBIAN
		case 'o':
			return true, stBIAO
		}
	case stBIAN:
		switch r {
		case 'g':
			return true, stBIANG
		}
	case stBIN:
		switch r {
		case 'g':
			return true, stBING
		}
	case stC:
		switch r {
		case 'a':
			return true, stCA
		case 'e':
			return true, stCE
		case 'h':
			return true, stCH
		case 'i':
			return true, stCI
		case 'o':
			return true, stCO
		case 'u':
			return true, stCU
		}
	case stCA:
		switch r {
		case 'i':
			return true, stCAI
		case 'n':
			return true, stCAN
		case 'o':
			return true, stCAO
		}
	case stCAN:
		switch r {
		case 'g':
			return true, stCANG
		}
	case stCE:
		switch r {
		case 'i':
			return true, stCEI
		case 'n':
			return true, stCEN
		}
	case stCEN:
		switch r {
		case 'g':
			return true, stCENG
		}
	case stCH:
		switch r {
		case 'a':
			return true, stCHA
		case 'e':
			return true, stCHE
		case 'i':
			return true, stCHI
		case 'o':
			return true, stCHO
		case 'u':
			return true, stCHU
		}
	case stCHA:
		switch r {
		case 'i':
			return true, stCHAI
		case 'n':
			return true, stCHAN
		case 'o':
			return true, stCHAO
		}
	case stCHAN:
		switch r {
		case 'g':
			return true, stCHANG
		}
	case stCHE:
		switch r {
		case 'n':
			return true, stCHEN
		}
	case stCHEN:
		switch r {
		case 'g':
			return true, stCHENG
		}
	case stCHO:
		switch r {
		case 'n':
			return true, stCHON
		case 'u':
			return true, stCHOU
		}
	case stCHON:
		switch r {
		case 'g':
			return true, stCHONG
		}
	case stCHU:
		switch r {
		case 'a':
			return true, stCHUA
		case 'i':
			return true, stCHUI
		case 'n':
			return true, stCHUN
		case 'o':
			return true, stCHUO
		}
	case stCHUA:
		switch r {
		case 'i':
			return true, stCHUAI
		case 'n':
			return true, stCHUAN
		}
	case stCHUAN:
		switch r {
		case 'g':
			return true, stCHUANG
		}
	case stCO:
		switch r {
		case 'n':
			return true, stCON
		case 'u':
			return true, stCOU
		}
	case stCON:
		switch r {
		case 'g':
			return true, stCONG
		}
	case stCU:
		switch r {
		case 'a':
			return true, stCUA
		case 'i':
			return true, stCUI
		case 'n':
			return true, stCUN
		case 'o':
			return true, stCUO
		}
	case stCUA:
		switch r {
		case 'n':
			return true, stCUAN
		}
	case stD:
		switch r {
		case 'a':
			return true, stDA
		case 'e':
			return true, stDE
		case 'i':
			return true, stDI
		case 'o':
			return true, stDO
		case 'u':
			return true, stDU
		}
	case stDA:
		switch r {
		case 'i':
			return true, stDAI
		case 'n':
			return true, stDAN
		case 'o':
			return true, stDAO
		}
	case stDAN:
		switch r {
		case 'g':
			return true, stDANG
		}
	case stDE:
		switch r {
		case 'i':
			return true, stDEI
		case 'n':
			return true, stDEN
		}
	case stDEN:
		switch r {
		case 'g':
			return true, stDENG
		}
	case stDI:
		switch r {
		case 'a':
			return true, stDIA
		case 'e':
			return true, stDIE
		case 'n':
			return true, stDIN
		case 'u':
			return true, stDIU
		}
	case stDIA:
		switch r {
		case 'n':
			return true, stDIAN
		case 'o':
			return true, stDIAO
		}
	case stDIN:
		switch r {
		case 'g':
			return true, stDING
		}
	case stDO:
		switch r {
		case 'n':
			return true, stDON
		case 'u':
			return true, stDOU
		}
	case stDON:
		switch r {
		case 'g':
			return true, stDONG
		}
	case stDU:
		switch r {
		case 'a':
			return true, stDUA
		case 'i':
			return true, stDUI
		case 'n':
			return true, stDUN
		case 'o':
			return true, stDUO
		}
	case stDUA:
		switch r {
		case 'n':
			return true, stDUAN
		}
	case stE:
		switch r {
		case 'i':
			return true, stEI
		case 'n':
			return true, stEN
		case 'r':
			return true, stER
		}
	case stEN:
		switch r {
		case 'g':
			return true, stENG
		}
	case stF:
		switch r {
		case 'a':
			return true, stFA
		case 'e':
			return true, stFE
		case 'i':
			return true, stFI
		case 'o':
			return true, stFO
		case 'u':
			return true, stFU
		}
	case stFA:
		switch r {
		case 'n':
			return true, stFAN
		}
	case stFAN:
		switch r {
		case 'g':
			return true, stFANG
		}
	case stFE:
		switch r {
		case 'i':
			return true, stFEI
		case 'n':
			return true, stFEN
		}
	case stFEN:
		switch r {
		case 'g':
			return true, stFENG
		}
	case stFI:
		switch r {
		case 'a':
			return true, stFIA
		}
	case stFIA:
		switch r {
		case 'o':
			return true, stFIAO
		}
	case stFO:
		switch r {
		case 'u':
			return true, stFOU
		}
	case stG:
		switch r {
		case 'a':
			return true, stGA
		case 'e':
			return true, stGE
		case 'o':
			return true, stGO
		case 'u':
			return true, stGU
		}
	case stGA:
		switch r {
		case 'i':
			return true, stGAI
		case 'n':
			return true, stGAN
		case 'o':
			return true, stGAO
		}
	case stGAN:
		switch r {
		case 'g':
			return true, stGANG
		}
	case stGE:
		switch r {
		case 'i':
			return true, stGEI
		case 'n':
			return true, stGEN
		}
	case stGEN:
		switch r {
		case 'g':
			return true, stGENG
		}
	case stGO:
		switch r {
		case 'n':
			return true, stGON
		case 'u':
			return true, stGOU
		}
	case stGON:
		switch r {
		case 'g':
			return true, stGONG
		}
	case stGU:
		switch r {
		case 'a':
			return true, stGUA
		case 'i':
			return true, stGUI
		case 'n':
			return true, stGUN
		case 'o':
			return true, stGUO
		}
	case stGUA:
		switch r {
		case 'i':
			return true, stGUAI
		case 'n':
			return true, stGUAN
		}
	case stGUAN:
		switch r {
		case 'g':
			return true, stGUANG
		}
	case stH:
		switch r {
		case 'a':
			return true, stHA
		case 'e':
			return true, stHE
		case 'm':
			return true, stHM
		case 'o':
			return true, stHO
		case 'u':
			return true, stHU
		}
	case stHA:
		switch r {
		case 'i':
			return true, stHAI
		case 'n':
			return true, stHAN
		case 'o':
			return true, stHAO
		}
	case stHAN:
		switch r {
		case 'g':
			return true, stHANG
		}
	case stHE:
		switch r {
		case 'i':
			return true, stHEI
		case 'n':
			return true, stHEN
		}
	case stHEN:
		switch r {
		case 'g':
			return true, stHENG
		}
	case stHO:
		switch r {
		case 'n':
			return true, stHON
		case 'u':
			return true, stHOU
		}
	case stHON:
		switch r {
		case 'g':
			return true, stHONG
		}
	case stHU:
		switch r {
		case 'a':
			return true, stHUA
		case 'i':
			return true, stHUI
		case 'n':
			return true, stHUN
		case 'o':
			return true, stHUO
		}
	case stHUA:
		switch r {
		case 'i':
			return true, stHUAI
		case 'n':
			return true, stHUAN
		}
	case stHUAN:
		switch r {
		case 'g':
			return true, stHUANG
		}
	case stJ:
		switch r {
		case 'i':
			return true, stJI
		case 'u':
			return true, stJU
		}
	case stJI:
		switch r {
		case 'a':
			return true, stJIA
		case 'e':
			return true, stJIE
		case 'n':
			return true, stJIN
		case 'o':
			return true, stJIO
		case 'u':
			return true, stJIU
		}
	case stJIA:
		switch r {
		case 'n':
			return true, stJIAN
		case 'o':
			return true, stJIAO
		}
	case stJIAN:
		switch r {
		case 'g':
			return true, stJIANG
		}
	case stJIN:
		switch r {
		case 'g':
			return true, stJING
		}
	case stJIO:
		switch r {
		case 'n':
			return true, stJION
		}
	case stJION:
		switch r {
		case 'g':
			return true, stJIONG
		}
	case stJU:
		switch r {
		case 'a':
			return true, stJUA
		case 'e':
			return true, stJUE
		case 'n':
			return true, stJUN
		}
	case stJUA:
		switch r {
		case 'n':
			return true, stJUAN
		}
	case stK:
		switch r {
		case 'a':
			return true, stKA
		case 'e':
			return true, stKE
		case 'o':
			return true, stKO
		case 'u':
			return true, stKU
		}
	case stKA:
		switch r {
		case 'i':
			return true, stKAI
		case 'n':
			return true, stKAN
		case 'o':
			return true, stKAO
		}
	case stKAN:
		switch r {
		case 'g':
			return true, stKANG
		}
	case stKE:
		switch r {
		case 'i':
			return true, stKEI
		case 'n':
			return true, stKEN
		}
	case stKEN:
		switch r {
		case 'g':
			return true, stKENG
		}
	case stKO:
		switch r {
		case 'n':
			return true, stKON
		case 'u':
			return true, stKOU
		}
	case stKON:
		switch r {
		case 'g':
			return true, stKONG
		}
	case stKU:
		switch r {
		case 'a':
			return true, stKUA
		case 'i':
			return true, stKUI
		case 'n':
			return true, stKUN
		case 'o':
			return true, stKUO
		}
	case stKUA:
		switch r {
		case 'i':
			return true, stKUAI
		case 'n':
			return true, stKUAN
		}
	case stKUAN:
		switch r {
		case 'g':
			return true, stKUANG
		}
	case stL:
		switch r {
		case 'a':
			return true, stLA
		case 'e':
			return true, stLE
		case 'i':
			return true, stLI
		case 'o':
			return true, stLO
		case 'u':
			return true, stLU
		case 'ü':
			return true, stLÜ
		}
	case stLA:
		switch r {
		case 'i':
			return true, stLAI
		case 'n':
			return true, stLAN
		case 'o':
			return true, stLAO
		}
	case stLAN:
		switch r {
		case 'g':
			return true, stLANG
		}
	case stLE:
		switch r {
		case 'i':
			return true, stLEI
		case 'n':
			return true, stLEN
		}
	case stLEN:
		switch r {
		case 'g':
			return true, stLENG
		}
	case stLI:
		switch r {
		case 'a':
			return true, stLIA
		case 'e':
			return true, stLIE
		case 'n':
			return true, stLIN
		case 'u':
			return true, stLIU
		}
	case stLIA:
		switch r {
		case 'n':
			return true, stLIAN
		case 'o':
			return true, stLIAO
		}
	case stLIAN:
		switch r {
		case 'g':
			return true, stLIANG
		}
	case stLIN:
		switch r {
		case 'g':
			return true, stLING
		}
	case stLO:
		switch r {
		case 'n':
			return true, stLON
		case 'u':
			return true, stLOU
		}
	case stLON:
		switch r {
		case 'g':
			return true, stLONG
		}
	case stLU:
		switch r {
		case 'a':
			return true, stLUA
		case 'n':
			return true, stLUN
		case 'o':
			return true, stLUO
		case ':':
			return true, stLÜ
		}
	case stLUA:
		switch r {
		case 'n':
			return true, stLUAN
		}
	case stLÜ:
		switch r {
		case 'e':
			return true, stLÜE
		}
	case stM:
		switch r {
		case 'a':
			return true, stMA
		case 'e':
			return true, stME
		case 'i':
			return true, stMI
		case 'o':
			return true, stMO
		case 'u':
			return true, stMU
		}
	case stMA:
		switch r {
		case 'i':
			return true, stMAI
		case 'n':
			return true, stMAN
		case 'o':
			return true, stMAO
		}
	case stMAN:
		switch r {
		case 'g':
			return true, stMANG
		}
	case stME:
		switch r {
		case 'i':
			return true, stMEI
		case 'n':
			return true, stMEN
		}
	case stMEN:
		switch r {
		case 'g':
			return true, stMENG
		}
	case stMI:
		switch r {
		case 'a':
			return true, stMIA
		case 'e':
			return true, stMIE
		case 'n':
			return true, stMIN
		case 'u':
			return true, stMIU
		}
	case stMIA:
		switch r {
		case 'n':
			return true, stMIAN
		case 'o':
			return true, stMIAO
		}
	case stMIN:
		switch r {
		case 'g':
			return true, stMING
		}
	case stMO:
		switch r {
		case 'u':
			return true, stMOU
		}
	case stN:
		switch r {
		case 'a':
			return true, stNA
		case 'e':
			return true, stNE
		case 'g':
			return true, stNG
		case 'i':
			return true, stNI
		case 'o':
			return true, stNO
		case 'u':
			return true, stNU
		case 'ü':
			return true, stNÜ
		}
	case stNA:
		switch r {
		case 'i':
			return true, stNAI
		case 'n':
			return true, stNAN
		case 'o':
			return true, stNAO
		}
	case stNAN:
		switch r {
		case 'g':
			return true, stNANG
		}
	case stNE:
		switch r {
		case 'i':
			return true, stNEI
		case 'n':
			return true, stNEN
		}
	case stNEN:
		switch r {
		case 'g':
			return true, stNENG
		}
	case stNI:
		switch r {
		case 'a':
			return true, stNIA
		case 'e':
			return true, stNIE
		case 'n':
			return true, stNIN
		case 'u':
			return true, stNIU
		}
	case stNIA:
		switch r {
		case 'n':
			return true, stNIAN
		case 'o':
			return true, stNIAO
		}
	case stNIAN:
		switch r {
		case 'g':
			return true, stNIANG
		}
	case stNIN:
		switch r {
		case 'g':
			return true, stNING
		}
	case stNO:
		switch r {
		case 'n':
			return true, stNON
		case 'u':
			return true, stNOU
		}
	case stNON:
		switch r {
		case 'g':
			return true, stNONG
		}
	case stNU:
		switch r {
		case 'a':
			return true, stNUA
		case 'n':
			return true, stNUN
		case 'o':
			return true, stNUO
		case ':':
			return true, stNÜ
		}
	case stNUA:
		switch r {
		case 'n':
			return true, stNUAN
		}
	case stNÜ:
		switch r {
		case 'e':
			return true, stNÜE
		}
	case stO:
		switch r {
		case 'u':
			return true, stOU
		}
	case stP:
		switch r {
		case 'a':
			return true, stPA
		case 'e':
			return true, stPE
		case 'i':
			return true, stPI
		case 'o':
			return true, stPO
		case 'u':
			return true, stPU
		}
	case stPA:
		switch r {
		case 'i':
			return true, stPAI
		case 'n':
			return true, stPAN
		case 'o':
			return true, stPAO
		}
	case stPAN:
		switch r {
		case 'g':
			return true, stPANG
		}
	case stPE:
		switch r {
		case 'i':
			return true, stPEI
		case 'n':
			return true, stPEN
		}
	case stPEN:
		switch r {
		case 'g':
			return true, stPENG
		}
	case stPI:
		switch r {
		case 'a':
			return true, stPIA
		case 'e':
			return true, stPIE
		case 'n':
			return true, stPIN
		}
	case stPIA:
		switch r {
		case 'n':
			return true, stPIAN
		case 'o':
			return true, stPIAO
		}
	case stPIN:
		switch r {
		case 'g':
			return true, stPING
		}
	case stPO:
		switch r {
		case 'u':
			return true, stPOU
		}
	case stQ:
		switch r {
		case 'i':
			return true, stQI
		case 'u':
			return true, stQU
		}
	case stQI:
		switch r {
		case 'a':
			return true, stQIA
		case 'e':
			return true, stQIE
		case 'n':
			return true, stQIN
		case 'o':
			return true, stQIO
		case 'u':
			return true, stQIU
		}
	case stQIA:
		switch r {
		case 'n':
			return true, stQIAN
		case 'o':
			return true, stQIAO
		}
	case stQIAN:
		switch r {
		case 'g':
			return true, stQIANG
		}
	case stQIN:
		switch r {
		case 'g':
			return true, stQING
		}
	case stQIO:
		switch r {
		case 'n':
			return true, stQION
		}
	case stQION:
		switch r {
		case 'g':
			return true, stQIONG
		}
	case stQU:
		switch r {
		case 'a':
			return true, stQUA
		case 'e':
			return true, stQUE
		case 'n':
			return true, stQUN
		}
	case stQUA:
		switch r {
		case 'n':
			return true, stQUAN
		}
	case stR:
		switch r {
		case 'a':
			return true, stRA
		case 'e':
			return true, stRE
		case 'i':
			return true, stRI
		case 'o':
			return true, stRO
		case 'u':
			return true, stRU
		}
	case stRA:
		switch r {
		case 'n':
			return true, stRAN
		case 'o':
			return true, stRAO
		}
	case stRAN:
		switch r {
		case 'g':
			return true, stRANG
		}
	case stRE:
		switch r {
		case 'n':
			return true, stREN
		}
	case stREN:
		switch r {
		case 'g':
			return true, stRENG
		}
	case stRO:
		switch r {
		case 'n':
			return true, stRON
		case 'u':
			return true, stROU
		}
	case stRON:
		switch r {
		case 'g':
			return true, stRONG
		}
	case stRU:
		switch r {
		case 'a':
			return true, stRUA
		case 'i':
			return true, stRUI
		case 'n':
			return true, stRUN
		case 'o':
			return true, stRUO
		}
	case stRUA:
		switch r {
		case 'n':
			return true, stRUAN
		}
	case stS:
		switch r {
		case 'a':
			return true, stSA
		case 'e':
			return true, stSE
		case 'h':
			return true, stSH
		case 'i':
			return true, stSI
		case 'o':
			return true, stSO
		case 'u':
			return true, stSU
		}
	case stSA:
		switch r {
		case 'i':
			return true, stSAI
		case 'n':
			return true, stSAN
		case 'o':
			return true, stSAO
		}
	case stSAN:
		switch r {
		case 'g':
			return true, stSANG
		}
	case stSE:
		switch r {
		case 'n':
			return true, stSEN
		}
	case stSEN:
		switch r {
		case 'g':
			return true, stSENG
		}
	case stSH:
		switch r {
		case 'a':
			return true, stSHA
		case 'e':
			return true, stSHE
		case 'i':
			return true, stSHI
		case 'o':
			return true, stSHO
		case 'u':
			return true, stSHU
		}
	case stSHA:
		switch r {
		case 'i':
			return true, stSHAI
		case 'n':
			return true, stSHAN
		case 'o':
			return true, stSHAO
		}
	case stSHAN:
		switch r {
		case 'g':
			return true, stSHANG
		}
	case stSHE:
		switch r {
		case 'i':
			return true, stSHEI
		case 'n':
			return true, stSHEN
		}
	case stSHEN:
		switch r {
		case 'g':
			return true, stSHENG
		}
	case stSHO:
		switch r {
		case 'u':
			return true, stSHOU
		}
	case stSHU:
		switch r {
		case 'a':
			return true, stSHUA
		case 'i':
			return true, stSHUI
		case 'n':
			return true, stSHUN
		case 'o':
			return true, stSHUO
		}
	case stSHUA:
		switch r {
		case 'i':
			return true, stSHUAI
		case 'n':
			return true, stSHUAN
		}
	case stSHUAN:
		switch r {
		case 'g':
			return true, stSHUANG
		}
	case stSO:
		switch r {
		case 'n':
			return true, stSON
		case 'u':
			return true, stSOU
		}
	case stSON:
		switch r {
		case 'g':
			return true, stSONG
		}
	case stSU:
		switch r {
		case 'a':
			return true, stSUA
		case 'i':
			return true, stSUI
		case 'n':
			return true, stSUN
		case 'o':
			return true, stSUO
		}
	case stSUA:
		switch r {
		case 'n':
			return true, stSUAN
		}
	case stT:
		switch r {
		case 'a':
			return true, stTA
		case 'e':
			return true, stTE
		case 'i':
			return true, stTI
		case 'o':
			return true, stTO
		case 'u':
			return true, stTU
		}
	case stTA:
		switch r {
		case 'i':
			return true, stTAI
		case 'n':
			return true, stTAN
		case 'o':
			return true, stTAO
		}
	case stTAN:
		switch r {
		case 'g':
			return true, stTANG
		}
	case stTE:
		switch r {
		case 'i':
			return true, stTEI
		case 'n':
			return true, stTEN
		}
	case stTEN:
		switch r {
		case 'g':
			return true, stTENG
		}
	case stTI:
		switch r {
		case 'a':
			return true, stTIA
		case 'e':
			return true, stTIE
		case 'n':
			return true, stTIN
		}
	case stTIA:
		switch r {
		case 'n':
			return true, stTIAN
		case 'o':
			return true, stTIAO
		}
	case stTIN:
		switch r {
		case 'g':
			return true, stTING
		}
	case stTO:
		switch r {
		case 'n':
			return true, stTON
		case 'u':
			return true, stTOU
		}
	case stTON:
		switch r {
		case 'g':
			return true, stTONG
		}
	case stTU:
		switch r {
		case 'a':
			return true, stTUA
		case 'i':
			return true, stTUI
		case 'n':
			return true, stTUN
		case 'o':
			return true, stTUO
		}
	case stTUA:
		switch r {
		case 'n':
			return true, stTUAN
		}
	case stW:
		switch r {
		case 'a':
			return true, stWA
		case 'e':
			return true, stWE
		case 'o':
			return true, stWO
		case 'u':
			return true, stWU
		}
	case stWA:
		switch r {
		case 'i':
			return true, stWAI
		case 'n':
			return true, stWAN
		}
	case stWAN:
		switch r {
		case 'g':
			return true, stWANG
		}
	case stWE:
		switch r {
		case 'i':
			return true, stWEI
		case 'n':
			return true, stWEN
		}
	case stWEN:
		switch r {
		case 'g':
			return true, stWENG
		}
	case stWO:
		switch r {
		case 'n':
			return true, stWON
		}
	case stWON:
		switch r {
		case 'g':
			return true, stWONG
		}
	case stX:
		switch r {
		case 'i':
			return true, stXI
		case 'u':
			return true, stXU
		}
	case stXI:
		switch r {
		case 'a':
			return true, stXIA
		case 'e':
			return true, stXIE
		case 'n':
			return true, stXIN
		case 'o':
			return true, stXIO
		case 'u':
			return true, stXIU
		}
	case stXIA:
		switch r {
		case 'n':
			return true, stXIAN
		case 'o':
			return true, stXIAO
		}
	case stXIAN:
		switch r {
		case 'g':
			return true, stXIANG
		}
	case stXIN:
		switch r {
		case 'g':
			return true, stXING
		}
	case stXIO:
		switch r {
		case 'n':
			return true, stXION
		}
	case stXION:
		switch r {
		case 'g':
			return true, stXIONG
		}
	case stXU:
		switch r {
		case 'a':
			return true, stXUA
		case 'e':
			return true, stXUE
		case 'n':
			return true, stXUN
		}
	case stXUA:
		switch r {
		case 'n':
			return true, stXUAN
		}
	case stY:
		switch r {
		case 'a':
			return true, stYA
		case 'e':
			return true, stYE
		case 'i':
			return true, stYI
		case 'o':
			return true, stYO
		case 'u':
			return true, stYU
		}
	case stYA:
		switch r {
		case 'n':
			return true, stYAN
		case 'o':
			return true, stYAO
		}
	case stYAN:
		switch r {
		case 'g':
			return true, stYANG
		}
	case stYI:
		switch r {
		case 'n':
			return true, stYIN
		}
	case stYIN:
		switch r {
		case 'g':
			return true, stYING
		}
	case stYO:
		switch r {
		case 'n':
			return true, stYON
		case 'u':
			return true, stYOU
		}
	case stYON:
		switch r {
		case 'g':
			return true, stYONG
		}
	case stYU:
		switch r {
		case 'a':
			return true, stYUA
		case 'e':
			return true, stYUE
		case 'n':
			return true, stYUN
		}
	case stYUA:
		switch r {
		case 'n':
			return true, stYUAN
		}
	case stZ:
		switch r {
		case 'a':
			return true, stZA
		case 'e':
			return true, stZE
		case 'h':
			return true, stZH
		case 'i':
			return true, stZI
		case 'o':
			return true, stZO
		case 'u':
			return true, stZU
		}
	case stZA:
		switch r {
		case 'i':
			return true, stZAI
		case 'n':
			return true, stZAN
		case 'o':
			return true, stZAO
		}
	case stZAN:
		switch r {
		case 'g':
			return true, stZANG
		}
	case stZE:
		switch r {
		case 'i':
			return true, stZEI
		case 'n':
			return true, stZEN
		}
	case stZEN:
		switch r {
		case 'g':
			return true, stZENG
		}
	case stZH:
		switch r {
		case 'a':
			return true, stZHA
		case 'e':
			return true, stZHE
		case 'i':
			return true, stZHI
		case 'o':
			return true, stZHO
		case 'u':
			return true, stZHU
		}
	case stZHA:
		switch r {
		case 'i':
			return true, stZHAI
		case 'n':
			return true, stZHAN
		case 'o':
			return true, stZHAO
		}
	case stZHAN:
		switch r {
		case 'g':
			return true, stZHANG
		}
	case stZHE:
		switch r {
		case 'i':
			return true, stZHEI
		case 'n':
			return true, stZHEN
		}
	case stZHEN:
		switch r {
		case 'g':
			return true, stZHENG
		}
	case stZHO:
		switch r {
		case 'n':
			return true, stZHON
		case 'u':
			return true, stZHOU
		}
	case stZHON:
		switch r {
		case 'g':
			return true, stZHONG
		}
	case stZHU:
		switch r {
		case 'a':
			return true, stZHUA
		case 'i':
			return true, stZHUI
		case 'n':
			return true, stZHUN
		case 'o':
			return true, stZHUO
		}
	case stZHUA:
		switch r {
		case 'i':
			return true, stZHUAI
		case 'n':
			return true, stZHUAN
		}
	case stZHUAN:
		switch r {
		case 'g':
			return true, stZHUANG
		}
	case stZO:
		switch r {
		case 'n':
			return true, stZON
		case 'u':
			return true, stZOU
		}
	case stZON:
		switch r {
		case 'g':
			return true, stZONG
		}
	case stZU:
		switch r {
		case 'a':
			return true, stZUA
		case 'i':
			return true, stZUI
		case 'n':
			return true, stZUN
		case 'o':
			return true, stZUO
		}
	case stZUA:
		switch r {
		case 'n':
			return true, stZUAN
		}
	}
	return false, 0
}

func (p Sound) special() bool {
	switch p {
	case A:
		return true
	case O:
		return true
	case E:
		return true
	case ER:
		return true
	case AI:
		return true
	case AO:
		return true
	case OU:
		return true
	case AN:
		return true
	case EN:
		return true
	case ANG:
		return true
	case ENG:
		return true
	case EI:
		return true
	default:
		return false
	}
}
