on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: run tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.6
    - name: Create build dir
      run: mkdir build
    - name: Build gen-dict
      run: go build -o build/gen-dict ./cmd/gen-dict
    - name: Build gen-numbers
      run: go build -o build/gen-numbers ./cmd/gen-numbers
    - name: Build gen-pinyin-parser
      run: go build -o build/gen-pinyin-parser ./cmd/gen-pinyin-parser
    - name: Build gen-simp-trad
      run: go build -o build/gen-simp-trad ./cmd/gen-simp-trad
    - name: Remove current generated code
      run: |
        rm dict/gen.bin
        rm numbers/gen.go
        rm pinyin/gen.go
        rm simplified/gen.go
    - name: Re-generate code
      run: |
        go generate ./pinyin
        go generate ./numbers
        go generate ./simplified
        go generate ./dict
    - name: Check for changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Error: Uncommitted changes found!"
          exit 1
        fi
    - name: Run tests
      run: go test ./...
